### PR TITLE
Remove filesystem token for Brew. Use crendential plugin

### PR DESCRIPTION
**Pull request by j-rivero**
The PR removes the injection of the GITHUB token into `jenkins-scripts/lib/_homebrew_github_setup.bash` to work using the same variable injected via credentials plugin. @scpeters if you please find a chance to test it, appreciated.

### CODE REVIEW

**Comment by scpeters** [comment]
the DSL modifies 2 jobs:

* [generic-release-homebrew_pull_request_updater](https://build.osrfoundation.org/job/generic-release-homebrew_pull_request_updater) for opening homebrew-simulation pull requests
* [generic-release-homebrew_pr_bottle_hash_updater](https://build.osrfoundation.org/job/generic-release-homebrew_pr_bottle_hash_updater/) for updating the bottle hashes after successfully building and uploading bottles

I'll test these two jobs separately

**Comment by scpeters** [comment]
> * [generic-release-homebrew_pull_request_updater](https://build.osrfoundation.org/job/generic-release-homebrew_pull_request_updater) for opening homebrew-simulation pull requests

this is easy to test; I'll just rerun the following job with this branch after deploying the DSL from this branch. I expect it to open a pull request to revert sdformat 15.1.1 back to sdformat 15.1.0 (I won't merge it). If it pushes a branch and opens a pull request, then it counts as a success

**Comment by scpeters** [comment]
> > * [generic-release-homebrew_pull_request_updater](https://build.osrfoundation.org/job/generic-release-homebrew_pull_request_updater) for opening homebrew-simulation pull requests
> 
> this is easy to test; I'll just rerun the following job with this branch after deploying the DSL from this branch. I expect it to open a pull request to revert sdformat 15.1.1 back to sdformat 15.1.0 (I won't merge it). If it pushes a branch and opens a pull request, then it counts as a success

deploying DSL: [Build Status](https://build.osrfoundation.org/job/_dsl_brew_release/938/) https://build.osrfoundation.org/job/_dsl_brew_release/938/

running generic-release-homebrew_pull_request_updater: [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_pull_request_updater/1607/) https://build.osrfoundation.org/job/generic-release-homebrew_pull_request_updater/1607/

**Comment by scpeters** [comment]
>> If it pushes a branch and opens a pull request, then it counts as a success
> 
> deploying DSL: [Build Status](https://build.osrfoundation.org/job/_dsl_brew_release/938/) https://build.osrfoundation.org/job/_dsl_brew_release/938/
> 
> running generic-release-homebrew_pull_request_updater: [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_pull_request_updater/1608/) https://build.osrfoundation.org/job/generic-release-homebrew_pull_request_updater/1608/

success! https://github.com/osrf/homebrew-simulation/pull/2891

**Review by scpeters — APPROVED** [review]
the code paths are the same between the two jobs, so I'm comfortable approving after that test

**Comment by j-rivero** [comment]
Great! Thanks so much for doing the test.

**Pull request merged**
