### PR TITLE
Added MFC compiler tools on Windows

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>

I added `qt5-winextras` in  `ign-gui` CI, but this requires `MFC compiler tools`. This PR install this dependency using the MSVC installer shell.

You can see the error in the CI [here](https://build.osrfoundation.org/job/ign_gui-pr-win/885/consoleFull#591808568aa60f765-a60a-427d-900c-dc128ab22287)

### CODE REVIEW

**Comment by ahcorde** [comment]
This PR https://github.com/ignitionrobotics/ign-gui/pull/250 requires to install `mesa[gles2]` and `mesa[egl]`. These two packages are not available in the configured vcpkg tag `2020.11`. We should use a newer version `2021.05.12`.

I think we should run a job to update the `_dls_core` job.

**Comment by ahcorde** [comment]
Related https://github.com/ignitionrobotics/docs/pull/190

**Comment by j-rivero** [comment]
> This PR [ignitionrobotics/ign-gui#250](https://github.com/ignitionrobotics/ign-gui/pull/250) requires to install `mesa[gles2]` and `mesa[egl]`. These two packages are not available in the configured vcpkg tag `2020.11`. We should use a newer version `2021.05.12`.

The update is going to block this PR or we can review and test it before going for the snapshot update?

**Comment by ahcorde** [comment]
I think you can review it and merge it, if it's fine

**Comment by j-rivero** [comment]
> I think you can review it and merge it, if it's fine

It is. Can we have a test build using this branch?

**Comment by j-rivero** [comment]
Please reopen if needed.

**Pull request closed without merging**
