### PR TITLE
Update the Garden collection/view on Jenkins

### PR DESCRIPTION
**Pull request by azeey**
I removed some redundant entries (`gz_*-install-pkg-focal-amd64`), use the `gz-sim7` job instead of `main` for gz-sim, and moved sdformat jobs to be grouped with similar jobs.

Questions for @j-rivero / @scpeters :

- I noticed that `ignition_sim7-install_bottle-homebrew-amd64` is missing. Does this exist under a different name?
- Also, I noticed the naming pattern changed for gz-sim, e.g, instead of `ign_gazebo-gz-7-win`, we now use `ign_gazebo-gz-sim7-win`. Not sure if that's intended.

### CODE REVIEW

**Comment by j-rivero** [comment]
> I noticed that `ignition_sim7-install_bottle-homebrew-amd64` is missing. Does this exist under a different name?

It was a bug. Fixed in https://github.com/gazebo-tooling/release-tools/pull/885

**Comment by j-rivero** [comment]
> Also, I noticed the naming pattern changed for gz-sim, e.g, instead of `ign_gazebo-gz-7-win`, we now use `ign_gazebo-gz-sim7-win`. Not sure if that's intended.

Also a bug.
 * Fixed by https://github.com/gazebo-tooling/release-tools/pull/886
 * I've renamed the job in Jenkins //cc @Crola1702 from https://build.osrfoundation.org/job/ign_gazebo-gz-sim7-win/ to https://build.osrfoundation.org/job/ign_gazebo-gz-7-win/
 * Modified this PR [d3d8fe2](https://github.com/gazebo-tooling/release-tools/pull/884/commits/d3d8fe285745e4894d965ec39df95fa5c437640a)

**Review by j-rivero — APPROVED** [review]
we should be good now, thanks.

**Comment by scpeters** [comment]
I commented about the `ignition-sim7` bottle testing job (it should be `gz-sim7`): https://github.com/gazebo-tooling/release-tools/pull/885#issuecomment-1460951173

**Pull request merged**
