### PR TITLE
Add Harmonic view and setup nightlies for bumped libraries

### PR DESCRIPTION
**Pull request by azeey**
For easier review, 09b35ca83a4ff08d9d8d7ee4b82b3aa4e4af4e48 simply copies the garden view to harmonic and f176c4314b32a97e37a7435094437bc9d2f5d3e updates the view to use main branches for bumped libraries. I removed the `install` jobs since I thought we set those up later, but I'm not sure. Finally, a823a83fb864bb2f5040af465278a6167c0029e5 sets up the nightlies for the bumped branches. 

I haven't made large changes to these files before, so I'd appreciate extra scrutiny during review.

Part of https://github.com/gazebo-tooling/release-tools/issues/856

### CODE REVIEW

**Comment by iche033** [comment]
changes look good to me here but I'll let someone else who's more familiar with release-tools give the final thumbs up

**Comment by j-rivero** [comment]
The CI job is reporting some change in `ign-garden` view that I'm not sure we want to do, like removing the debbuilders from it. Problem was probably there from before this PR. I'll try to fix it.

```diff
Only in /tmp/pr_xml_configuration: gz-harmonic-debbuilder.xml
Only in /tmp/pr_xml_configuration: gz_harmonic-install-pkg-focal-amd64.xml
diff -ur -I '.*<id>dashboard_portlet_.*</id>.*' /tmp/current_xml_configuration/ign-garden.xml /tmp/pr_xml_configuration/ign-garden.xml
--- /tmp/current_xml_configuration/ign-garden.xml	2022-11-17 23:35:39.661301632 +0000
+++ /tmp/pr_xml_configuration/ign-garden.xml	2022-11-17 23:34:05.508943480 +0000
@@ -4,22 +4,6 @@
     <properties class='hudson.model.View$PropertyList'></properties>
     <jobNames>
         <comparator class='hudson.util.CaseInsensitiveComparator'></comparator>
-        <string>gz-cmake3-debbuilder</string>
-        <string>gz-common5-debbuilder</string>
-        <string>gz-fuel-tools8-debbuilder</string>
-        <string>gz-garden-debbuilder</string>
-        <string>gz-gui7-debbuilder</string>
-        <string>gz-launch6-debbuilder</string>
-        <string>gz-math7-debbuilder</string>
-        <string>gz-msgs9-debbuilder</string>
-        <string>gz-physics6-debbuilder</string>
-        <string>gz-plugin2-debbuilder</string>
-        <string>gz-rendering7-debbuilder</string>
-        <string>gz-sensors7-debbuilder</string>
-        <string>gz-sim7-debbuilder</string>
-        <string>gz-tools2-debbuilder</string>
-        <string>gz-transport12-debbuilder</string>
-        <string>gz-utils2-debbuilder</string>
         <string>gz_cmake3-install-pkg-focal-amd64</string>
         <string>gz_common5-install-pkg-focal-amd64</string>
         <string>gz_fuel-tools8-install-pkg-focal-amd64</string>
@@ -118,7 +102,6 @@
         <string>sdformat-ci-sdformat13-homebrew-amd64</string>
         <string>sdformat-install-sdformat12_pkg-focal-amd64</string>
         <string>sdformat-sdf-13-win</string>
-        <string>sdformat13-debbuilder</string>
     </jobNames>
     <jobFilters></jobFilters>
     <columns>
Only in /tmp/pr_xml_configuration: ign-gui8-debbuilder.xml
Only in /tmp/pr_xml_configuration: ign-harmonic.xml
Only in /tmp/pr_xml_configuration: ign-launch8-debbuilder.xml
Only in /tmp/pr_xml_configuration: ign-rendering8-debbuilder.xml
Only in /tmp/pr_xml_configuration: ign-sensors8-debbuilder.xml
Only in /tmp/pr_xml_configuration: ign-sim8-debbuilder.xml
Only in /tmp/pr_xml_configuration: ign_harmonic-ci-win.xml
Only in /tmp/current_xml_configuration: ignition-garden-nightly-scheduler.xml
Only in /tmp/pr_xml_configuration: ignition-harmonic-nightly-scheduler.xml
Only in /tmp/pr_xml_configuration: ignition_harmonic-ci-main-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_harmonic-install-pkg_ros_bootstrap-any-manual.xml
Only in /tmp/pr_xml_configuration: ignition_harmonic-install_bottle-homebrew-amd64.xml
```

**Comment by azeey** [comment]
hmm, Looking at https://github.com/gazebo-tooling/release-tools/blob/388e2f11e40fb6497d9e39b7f3845e10c499ea48/jenkins-scripts/dsl/ignition_collection.dsl#L207-L306, I don't see any debbuilder jobs listed in any collection. Also, on build.osrfoundation.org, only Garden has debbuilder jobs.


However, I do see in https://github.com/gazebo-tooling/release-tools/blob/388e2f11e40fb6497d9e39b7f3845e10c499ea48/jenkins-scripts/dsl/ignition_collection.dsl#L494-L497 that the debbuilder jobs are added for the nightly collection, which was Garden right before this PR.

**Comment by j-rivero** [comment]
>  that the debbuilder jobs are added for the nightly collection, which was Garden right before this PR.

Yep, that is the current behaviour, I was thinking if we want to change it to add debbuilder to all the views. Anyway, that would be better done in a different PR. Approving and merging.

**Review by j-rivero — APPROVED** [review]

**Pull request merged**
