### PR TITLE
Change daily Linux ci jobs (-ci-${branch}) to be based on gz-collections.yaml

### PR DESCRIPTION
**Pull request by j-rivero**
Remove the protection in `gazebo_libs` after Harmonic jobs were ready to generate the -ci-${branch}- jobs for Linux. Remove the corresponding code in ignition.dsl and sdformat.dsl. I would expect some changes in the branch names now that we are consistent with the yaml spec but the number of jobs and the testing done should be equivalent.

@Crola1702 @Blast545 For the buildfarmer board: we probably want to use the new log of jobs generated that help to remove the hardcoded values and would be auto-updated if something change at any point.

"+0 -172 lines" :grinning:

### CODE REVIEW

**Comment by j-rivero** [comment]
> @Crola1702 @Blast545 For the buildfarmer board: we probably want to use the new log of jobs generated that help to remove the hardcoded values and would be auto-updated if something change at any point.

The CI diff looks good to me. Added the jobs for Citadel, Fortress, Garden and Ionic:
```diff
diff -ur /tmp/current_log_generated/jobs.txt /tmp/pr_log_generated/jobs.txt
--- /tmp/current_log_generated/jobs.txt	2023-10-25 15:12:25.625167312 +0000
+++ /tmp/pr_log_generated/jobs.txt	2023-10-25 15:10:25.473058027 +0000
@@ -1,19 +1,83 @@
+branch_ci citadel ign_cmake-ci-ign-cmake2-bionic-amd64
+branch_ci citadel ign_tools-ci-ign-tools1-bionic-amd64
+branch_ci citadel ign_math-ci-ign-math6-bionic-amd64
+branch_ci citadel ign_plugin-ci-ign-plugin1-bionic-amd64
+branch_ci citadel ign_common-ci-ign-common3-bionic-amd64
+branch_ci citadel ign_msgs-ci-ign-msgs5-bionic-amd64
+branch_ci citadel ign_rendering-ci-ign-rendering3-bionic-amd64
+branch_ci citadel sdformat-ci-sdf9-bionic-amd64
+branch_ci fortress sdformat-ci-sdf12-focal-amd64
+branch_ci garden sdformat-ci-sdf13-focal-amd64
 branch_ci harmonic sdformat-ci-sdf14-jammy-amd64
+branch_ci ionic sdformat-ci-main-jammy-amd64
+branch_ci citadel ign_fuel_tools-ci-ign-fuel-tools4-bionic-amd64
+branch_ci citadel ign_transport-ci-ign-transport8-bionic-amd64
+branch_ci citadel ign_gui-ci-ign-gui3-bionic-amd64
+branch_ci citadel ign_sensors-ci-ign-sensors3-bionic-amd64
+branch_ci citadel ign_physics-ci-ign-physics2-bionic-amd64
+branch_ci citadel ign_gazebo-ci-ign-gazebo3-bionic-amd64
+branch_ci citadel ign_launch-ci-ign-launch2-bionic-amd64
+branch_ci fortress gz_cmake-ci-ign-cmake2-focal-amd64
+branch_ci garden gz_cmake-ci-gz-cmake3-focal-amd64
 branch_ci harmonic gz_cmake-ci-gz-cmake3-jammy-amd64
+branch_ci ionic gz_cmake-ci-main-jammy-amd64
+branch_ci fortress gz_tools-ci-ign-tools1-focal-amd64
+branch_ci garden gz_tools-ci-gz-tools2-focal-amd64
 branch_ci harmonic gz_tools-ci-gz-tools2-jammy-amd64
+branch_ci ionic gz_tools-ci-gz-tools2-jammy-amd64
+branch_ci __upcoming__ gz_tools-ci-main-jammy-amd64
+branch_ci fortress gz_utils-ci-ign-utils1-focal-amd64
+branch_ci garden gz_utils-ci-gz-utils2-focal-amd64
 branch_ci harmonic gz_utils-ci-gz-utils2-jammy-amd64
+branch_ci ionic gz_utils-ci-main-jammy-amd64
+branch_ci fortress gz_math-ci-ign-math6-focal-amd64
+branch_ci garden gz_math-ci-gz-math7-focal-amd64
 branch_ci harmonic gz_math-ci-gz-math7-jammy-amd64
+branch_ci ionic gz_math-ci-main-jammy-amd64
+branch_ci fortress gz_plugin-ci-ign-plugin1-focal-amd64
+branch_ci garden gz_plugin-ci-gz-plugin2-focal-amd64
 branch_ci harmonic gz_plugin-ci-gz-plugin2-jammy-amd64
+branch_ci ionic gz_plugin-ci-main-jammy-amd64
+branch_ci fortress gz_common-ci-ign-common4-focal-amd64
+branch_ci garden gz_common-ci-gz-common5-focal-amd64
 branch_ci harmonic gz_common-ci-gz-common5-jammy-amd64
+branch_ci ionic gz_common-ci-main-jammy-amd64
+branch_ci fortress gz_msgs-ci-ign-msgs8-focal-amd64
+branch_ci garden gz_msgs-ci-gz-msgs9-focal-amd64
 branch_ci harmonic gz_msgs-ci-gz-msgs10-jammy-amd64
+branch_ci ionic gz_msgs-ci-main-jammy-amd64
+branch_ci fortress gz_rendering-ci-ign-rendering6-focal-amd64
+branch_ci garden gz_rendering-ci-gz-rendering7-focal-amd64
 branch_ci harmonic gz_rendering-ci-gz-rendering8-jammy-amd64
+branch_ci ionic gz_rendering-ci-main-jammy-amd64
+branch_ci fortress gz_fuel_tools-ci-ign-fuel-tools7-focal-amd64
+branch_ci garden gz_fuel_tools-ci-gz-fuel-tools8-focal-amd64
 branch_ci harmonic gz_fuel_tools-ci-gz-fuel-tools9-jammy-amd64
+branch_ci ionic gz_fuel_tools-ci-main-jammy-amd64
+branch_ci fortress gz_transport-ci-ign-transport11-focal-amd64
+branch_ci garden gz_transport-ci-gz-transport12-focal-amd64
 branch_ci harmonic gz_transport-ci-gz-transport13-jammy-amd64
+branch_ci ionic gz_transport-ci-main-jammy-amd64
+branch_ci fortress gz_gui-ci-ign-gui6-focal-amd64
+branch_ci garden gz_gui-ci-gz-gui7-focal-amd64
 branch_ci harmonic gz_gui-ci-gz-gui8-jammy-amd64
+branch_ci ionic gz_gui-ci-main-jammy-amd64
+branch_ci fortress gz_sensors-ci-ign-sensors7-focal-amd64
+branch_ci garden gz_sensors-ci-gz-sensors7-focal-amd64
 branch_ci harmonic gz_sensors-ci-gz-sensors8-jammy-amd64
+branch_ci ionic gz_sensors-ci-main-jammy-amd64
+branch_ci fortress gz_physics-ci-ign-physics6-focal-amd64
+branch_ci garden gz_physics-ci-gz-physics6-focal-amd64
 branch_ci harmonic gz_physics-ci-gz-physics7-jammy-amd64
+branch_ci ionic gz_physics-ci-main-jammy-amd64
+branch_ci fortress gz_sim-ci-ign-sim6-focal-amd64
+branch_ci garden gz_sim-ci-gz-sim7-focal-amd64
 branch_ci harmonic gz_sim-ci-gz-sim8-jammy-amd64
+branch_ci ionic gz_sim-ci-main-jammy-amd64
+branch_ci fortress gz_launch-ci-ign-launch5-focal-amd64
+branch_ci garden gz_launch-ci-gz-launch6-focal-amd64
 branch_ci harmonic gz_launch-ci-gz-launch7-jammy-amd64
+branch_ci ionic gz_launch-ci-main-jammy-amd64
 unofficial_wrappers_install_pkg_ci garden ros_gzgarden_bridge-install-pkg_humble-ci-jammy-amd64
 unofficial_wrappers_install_pkg_ci garden ros_gzgarden_bridge-install-pkg_iron-ci-jammy-amd64
 unofficial_wrappers_install_pkg_ci harmonic ros_gzharmonic_bridge-install-pkg_iron-ci-jammy-amd64
```

**Review by Crola1702 — APPROVED** [review]
LGTM.

As far as I understand, this implies that new `gz_...` jobs are added, but `ignition_...` ones are kept, and gz version now matches linux distribution, right?

---

Just for the record, I see:
* new `ign_cmake-ci-ign-cmake2-bionic-amd64` (although cmake2-focal is tracked in fortress)
* `ignition_common-ci-ign-common3-focal-amd64` -> `ign_common-ci-ign-common3-bionic-amd64`
* `ignition_math-ci-ign-math6-focal-amd64` -> `gz_math-ci-ign-math6-focal-amd64`
* `ignition_physics-ci-gz-physics6-focal-amd64` -> `gz_physics-ci-gz-physics6-focal-amd64`
* etc...

**Comment by j-rivero** [comment]
> As far as I understand, this implies that new `gz_...` jobs are added, but `ignition_...` ones are kept, and gz version now matches linux distribution, right?

Some `ignition` names are kept, the ones for Citadel that are not changed in the `gz-collections.yaml` file. You can see them at the end of the list of current jobs and new jobs using bionic:

```diff
Only in /tmp/current_xml_configuration: ignition_cmake-ci-gz-cmake3-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_cmake-ci-ign-cmake2-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_cmake-ci-main-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_common-ci-gz-common5-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_common-ci-ign-common1-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_common-ci-ign-common3-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_common-ci-ign-common4-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_common-ci-main-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_fuel-tools-ci-gz-fuel-tools8-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_fuel-tools-ci-gz-fuel-tools9-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_fuel-tools-ci-ign-fuel-tools1-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_fuel-tools-ci-ign-fuel-tools4-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_fuel-tools-ci-ign-fuel-tools7-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_fuel-tools-ci-main-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_gazebo-ci-gz-sim7-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_gazebo-ci-gz-sim8-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_gazebo-ci-ign-gazebo3-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_gazebo-ci-ign-gazebo6-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_gazebo-ci-main-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_gui-ci-gz-gui7-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_gui-ci-gz-gui8-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_gui-ci-ign-gui0-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_gui-ci-ign-gui3-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_gui-ci-ign-gui6-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_gui-ci-main-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_launch-ci-gz-launch6-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_launch-ci-gz-launch7-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_launch-ci-ign-launch2-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_launch-ci-ign-launch5-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_launch-ci-main-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_math-ci-gz-math7-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_math-ci-ign-math4-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_math-ci-ign-math6-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_math-ci-main-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_msgs-ci-gz-msgs10-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_msgs-ci-gz-msgs9-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_msgs-ci-ign-msgs1-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_msgs-ci-ign-msgs5-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_msgs-ci-ign-msgs8-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_msgs-ci-main-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_physics-ci-gz-physics6-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_physics-ci-gz-physics7-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_physics-ci-ign-physics2-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_physics-ci-ign-physics5-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_physics-ci-main-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_plugin-ci-gz-plugin2-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_plugin-ci-ign-plugin1-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_plugin-ci-main-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_rendering-ci-gz-rendering7-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_rendering-ci-gz-rendering8-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_rendering-ci-ign-rendering3-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_rendering-ci-ign-rendering6-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_rendering-ci-main-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_sensors-ci-gz-sensors7-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_sensors-ci-gz-sensors8-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_sensors-ci-ign-sensors3-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_sensors-ci-ign-sensors6-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_sensors-ci-main-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_tools-ci-gz-tools2-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_tools-ci-ign-tools1-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_tools-ci-main-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_transport-ci-gz-transport12-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_transport-ci-gz-transport13-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_transport-ci-ign-transport11-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_transport-ci-ign-transport4-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_transport-ci-ign-transport8-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_transport-ci-main-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_utils-ci-gz-utils2-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_utils-ci-ign-utils1-focal-amd64.xml
Only in /tmp/current_xml_configuration: ignition_utils-ci-main-focal-amd64.xml
Only in /tmp/current_xml_configuration: sdformat-ci-main-focal-amd64.xml
Only in /tmp/current_xml_configuration: sdformat-ci-main-focal-i386.xml
Only in /tmp/current_xml_configuration: sdformat-ci-pr_any-ubuntu_auto-amd64.xml
Only in /tmp/current_xml_configuration: sdformat-ci-sdformat12-focal-amd64.xml
Only in /tmp/current_xml_configuration: sdformat-ci-sdformat13-focal-amd64.xml
Only in /tmp/current_xml_configuration: sdformat-ci-sdformat14-focal-amd64.xml
Only in /tmp/current_xml_configuration: sdformat-ci-sdformat6-focal-amd64.xml
Only in /tmp/current_xml_configuration: sdformat-ci-sdformat9-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_cmake-ci-gz-cmake3-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_cmake-ci-ign-cmake2-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_cmake-ci-main-jammy-amd64.xml
Only in /tmp/pr_xml_configuration: gz_common-ci-gz-common5-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_common-ci-ign-common4-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_common-ci-main-jammy-amd64.xml
Only in /tmp/pr_xml_configuration: gz_fuel_tools-ci-gz-fuel-tools8-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_fuel_tools-ci-ign-fuel-tools7-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_fuel_tools-ci-main-jammy-amd64.xml
Only in /tmp/pr_xml_configuration: gz_gui-ci-gz-gui7-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_gui-ci-ign-gui6-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_gui-ci-main-jammy-amd64.xml
Only in /tmp/pr_xml_configuration: gz_launch-ci-gz-launch6-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_launch-ci-ign-launch5-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_launch-ci-main-jammy-amd64.xml
Only in /tmp/pr_xml_configuration: gz_math-ci-gz-math7-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_math-ci-ign-math6-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_math-ci-main-jammy-amd64.xml
Only in /tmp/pr_xml_configuration: gz_msgs-ci-gz-msgs9-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_msgs-ci-ign-msgs8-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_msgs-ci-main-jammy-amd64.xml
Only in /tmp/pr_xml_configuration: gz_physics-ci-gz-physics6-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_physics-ci-ign-physics6-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_physics-ci-main-jammy-amd64.xml
Only in /tmp/pr_xml_configuration: gz_plugin-ci-gz-plugin2-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_plugin-ci-ign-plugin1-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_plugin-ci-main-jammy-amd64.xml
Only in /tmp/pr_xml_configuration: gz_rendering-ci-gz-rendering7-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_rendering-ci-ign-rendering6-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_rendering-ci-main-jammy-amd64.xml
Only in /tmp/pr_xml_configuration: gz_sensors-ci-gz-sensors7-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_sensors-ci-ign-sensors7-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_sensors-ci-main-jammy-amd64.xml
Only in /tmp/pr_xml_configuration: gz_sim-ci-gz-sim7-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_sim-ci-ign-sim6-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_sim-ci-main-jammy-amd64.xml
Only in /tmp/pr_xml_configuration: gz_tools-ci-gz-tools2-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_tools-ci-ign-tools1-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_tools-ci-main-jammy-amd64.xml
Only in /tmp/pr_xml_configuration: gz_transport-ci-gz-transport12-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_transport-ci-ign-transport11-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_transport-ci-main-jammy-amd64.xml
Only in /tmp/pr_xml_configuration: gz_utils-ci-gz-utils2-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_utils-ci-ign-utils1-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_utils-ci-main-jammy-amd64.xml
Only in /tmp/pr_xml_configuration: ign_cmake-ci-ign-cmake2-bionic-amd64.xml
Only in /tmp/pr_xml_configuration: ign_common-ci-ign-common3-bionic-amd64.xml
Only in /tmp/pr_xml_configuration: ign_fuel_tools-ci-ign-fuel-tools4-bionic-amd64.xml
Only in /tmp/pr_xml_configuration: ign_gazebo-ci-ign-gazebo3-bionic-amd64.xml
Only in /tmp/pr_xml_configuration: ign_gui-ci-ign-gui3-bionic-amd64.xml
Only in /tmp/pr_xml_configuration: ign_launch-ci-ign-launch2-bionic-amd64.xml
Only in /tmp/pr_xml_configuration: ign_math-ci-ign-math6-bionic-amd64.xml
Only in /tmp/pr_xml_configuration: ign_msgs-ci-ign-msgs5-bionic-amd64.xml
Only in /tmp/pr_xml_configuration: ign_physics-ci-ign-physics2-bionic-amd64.xml
Only in /tmp/pr_xml_configuration: ign_plugin-ci-ign-plugin1-bionic-amd64.xml
Only in /tmp/pr_xml_configuration: ign_rendering-ci-ign-rendering3-bionic-amd64.xml
Only in /tmp/pr_xml_configuration: ign_sensors-ci-ign-sensors3-bionic-amd64.xml
Only in /tmp/pr_xml_configuration: ign_tools-ci-ign-tools1-bionic-amd64.xml
Only in /tmp/pr_xml_configuration: ign_transport-ci-ign-transport8-bionic-amd64.xml
Only in /tmp/pr_xml_configuration: sdformat-ci-main-jammy-amd64.xml
Only in /tmp/pr_xml_configuration: sdformat-ci-sdf12-focal-amd64.xml
Only in /tmp/pr_xml_configuration: sdformat-ci-sdf13-focal-amd64.xml
Only in /tmp/pr_xml_configuration: sdformat-ci-sdf9-bionic-amd64.xml
```

**Comment by j-rivero** [comment]
Please also note that there are other changes: removed outdated branches, change in names to match the yaml file, etc. Here is a meld capture from comparing old and new: 
Screenshot from 2023-10-26 13-04-49

**Pull request merged**
