### PR TITLE
Implement the gz_*-install jobs for Garden

### PR DESCRIPTION
**Pull request by j-rivero**
As part of #578, the PR should generate the gz_*-install- jobs for testing the installation of the new gz packages.

New PR to come for implementing the -install_bottle- jobs for gz.

### CODE REVIEW

**Comment by j-rivero** [comment]
github actions where are you? :)

**Comment by j-rivero** [comment]
> Only in /tmp/current_xml_configuration: gz_sim3-install-pkg-focal-amd64.xml
> Only in /tmp/current_xml_configuration: gz_sim6-install-pkg-focal-amd64.xml

No good.

**Comment by j-rivero** [comment]
Changes:
```diff
Only in /tmp/pr_xml_configuration: gz_cmake3-install-pkg-focal-amd64.xml
Only in /tmp/current_xml_configuration: gz_common-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_common1-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_common5-install-pkg-focal-amd64.xml
Only in /tmp/current_xml_configuration: gz_fuel-tools-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_fuel-tools1-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_fuel-tools8-install-pkg-focal-amd64.xml
Only in /tmp/current_xml_configuration: gz_gui-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_gui0-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_gui7-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_launch6-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_math7-install-pkg-focal-amd64.xml
Only in /tmp/current_xml_configuration: gz_msgs-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_msgs1-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_msgs9-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_physics6-install-pkg-focal-amd64.xml
Only in /tmp/current_xml_configuration: gz_plugin-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_plugin1-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_plugin2-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_rendering7-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_sensors7-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_sim7-install-pkg-focal-amd64.xml
Only in /tmp/current_xml_configuration: gz_tools-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_tools1-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_tools2-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_transport12-install-pkg-focal-amd64.xml
Only in /tmp/current_xml_configuration: gz_utils-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_utils1-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_utils2-install-pkg-focal-amd64.xml
diff -ur -I '.*<id>dashboard_portlet_.*</id>.*' /tmp/current_xml_configuration/ign-garden.xml /tmp/pr_xml_configuration/ign-garden.xml
--- /tmp/current_xml_configuration/ign-garden.xml	2022-10-07 15:58:28.493946524 +0000
+++ /tmp/pr_xml_configuration/ign-garden.xml	2022-10-07 15:57:10.374219661 +0000
@@ -20,22 +20,22 @@
         <string>gz-tools2-debbuilder</string>
         <string>gz-transport12-debbuilder</string>
         <string>gz-utils2-debbuilder</string>
-        <string>gz_cmake2-install-pkg-focal-amd64</string>
-        <string>gz_common4-install-pkg-focal-amd64</string>
-        <string>gz_fuel-tools7-install-pkg-focal-amd64</string>
+        <string>gz_cmake3-install-pkg-focal-amd64</string>
+        <string>gz_common5-install-pkg-focal-amd64</string>
+        <string>gz_fuel-tools8-install-pkg-focal-amd64</string>
         <string>gz_garden-install-pkg-focal-amd64</string>
-        <string>gz_gazebo6-install-pkg-focal-amd64</string>
-        <string>gz_gui6-install-pkg-focal-amd64</string>
-        <string>gz_launch5-install-pkg-focal-amd64</string>
-        <string>gz_math6-install-pkg-focal-amd64</string>
-        <string>gz_msgs8-install-pkg-focal-amd64</string>
-        <string>gz_physics5-install-pkg-focal-amd64</string>
-        <string>gz_plugin-install-pkg-focal-amd64</string>
-        <string>gz_rendering6-install-pkg-focal-amd64</string>
-        <string>gz_sensors6-install-pkg-focal-amd64</string>
-        <string>gz_tools-install-pkg-focal-amd64</string>
-        <string>gz_transport11-install-pkg-focal-amd64</string>
-        <string>gz_utils-install-pkg-focal-amd64</string>
+        <string>gz_gazebo7-install-pkg-focal-amd64</string>
+        <string>gz_gui7-install-pkg-focal-amd64</string>
+        <string>gz_launch6-install-pkg-focal-amd64</string>
+        <string>gz_math7-install-pkg-focal-amd64</string>
+        <string>gz_msgs9-install-pkg-focal-amd64</string>
+        <string>gz_physics6-install-pkg-focal-amd64</string>
+        <string>gz_plugin2-install-pkg-focal-amd64</string>
+        <string>gz_rendering7-install-pkg-focal-amd64</string>
+        <string>gz_sensors7-install-pkg-focal-amd64</string>
+        <string>gz_tools2-install-pkg-focal-amd64</string>
+        <string>gz_transport12-install-pkg-focal-amd64</string>
+        <string>gz_utils2-install-pkg-focal-amd64</string>
         <string>ign_cmake-gz-3-win</string>
         <string>ign_common-gz-5-win</string>
         <string>ign_fuel-tools-gz-8-win</string>
Only in /tmp/pr_xml_configuration: ignition_cmake3-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_common5-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_fuel-tools8-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_gui7-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_launch6-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_math7-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_msgs9-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_physics6-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_plugin2-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_rendering7-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_sensors7-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_sim-ci-gz-sim7-windows7-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_sim-ci-main-windows7-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_sim-ci-manual_any.xml
Only in /tmp/pr_xml_configuration: ignition_sim-ci-pr_any-windows7-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_tools2-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_transport12-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_utils2-install_bottle-homebrew-amd64.xml
```

**Review by scpeters — APPROVED** [review]

**Comment by scpeters** [comment]
possible fallout from this PR:

* [Build Status](https://build.osrfoundation.org/job/ignition_sim-ci-main-windows7-amd64/1/) https://build.osrfoundation.org/job/ignition_sim-ci-main-windows7-amd64/1/

~~~
C:\Jenkins\workspace\ignition_sim-ci-main-windows7-amd64>call
 "./scripts/jenkins-scripts/ign_sim-default-devel-windows-amd64.bat" 
'"./scripts/jenkins-scripts/ign_sim-default-devel-windows-amd64.bat"' is not recognized as an internal or external command,
operable program or batch file.
~~~

**Pull request merged**
