### PR TITLE
ignition.dsl: add install jobs for garden pkgs

### PR DESCRIPTION
**Pull request by scpeters**
Signed-off-by: Steve Peters <scpeters@openrobotics.org>

### CODE REVIEW

**Comment by scpeters** [comment]
testing

[Build Status](https://build.osrfoundation.org/job/_dsl_ignition/1397/) https://build.osrfoundation.org/job/_dsl_ignition/1397/

~~~
Added items:
    GeneratedJob{name='ignition_cmake3-install-pkg-focal-amd64'}
    GeneratedJob{name='gz_cmake3-install-pkg-focal-amd64'}
    GeneratedJob{name='ignition_common5-install-pkg-focal-amd64'}
    GeneratedJob{name='gz_common5-install-pkg-focal-amd64'}
    GeneratedJob{name='ignition_fuel-tools8-install-pkg-focal-amd64'}
    GeneratedJob{name='gz_fuel-tools8-install-pkg-focal-amd64'}
    GeneratedJob{name='ignition_gazebo-install-pkg-focal-amd64'}
    GeneratedJob{name='gz_sim-install-pkg-focal-amd64'}
    GeneratedJob{name='ignition_gui7-install-pkg-focal-amd64'}
    GeneratedJob{name='gz_gui7-install-pkg-focal-amd64'}
    GeneratedJob{name='ignition_launch6-install-pkg-focal-amd64'}
    GeneratedJob{name='gz_launch6-install-pkg-focal-amd64'}
    GeneratedJob{name='ignition_math7-install-pkg-focal-amd64'}
    GeneratedJob{name='gz_math7-install-pkg-focal-amd64'}
    GeneratedJob{name='ignition_msgs9-install-pkg-focal-amd64'}
    GeneratedJob{name='gz_msgs9-install-pkg-focal-amd64'}
    GeneratedJob{name='ignition_physics6-install-pkg-focal-amd64'}
    GeneratedJob{name='gz_physics6-install-pkg-focal-amd64'}
    GeneratedJob{name='ignition_plugin2-install-pkg-focal-amd64'}
    GeneratedJob{name='gz_plugin2-install-pkg-focal-amd64'}
    GeneratedJob{name='ignition_rendering7-install-pkg-focal-amd64'}
    GeneratedJob{name='gz_rendering7-install-pkg-focal-amd64'}
    GeneratedJob{name='ignition_sensors7-install-pkg-focal-amd64'}
    GeneratedJob{name='gz_sensors7-install-pkg-focal-amd64'}
    GeneratedJob{name='ignition_tools2-install-pkg-focal-amd64'}
    GeneratedJob{name='gz_tools2-install-pkg-focal-amd64'}
    GeneratedJob{name='ignition_transport12-install-pkg-focal-amd64'}
    GeneratedJob{name='gz_transport12-install-pkg-focal-amd64'}
    GeneratedJob{name='ignition_utils2-install-pkg-focal-amd64'}
    GeneratedJob{name='gz_utils2-install-pkg-focal-amd64'}
    GeneratedJob{name='ignition_cmake3-install_bottle-homebrew-amd64'}
    GeneratedJob{name='ignition_common5-install_bottle-homebrew-amd64'}
    GeneratedJob{name='ignition_fuel-tools8-install_bottle-homebrew-amd64'}
    GeneratedJob{name='ignition_gazebo-install_bottle-homebrew-amd64'}
    GeneratedJob{name='ignition_gui7-install_bottle-homebrew-amd64'}
    GeneratedJob{name='ignition_launch6-install_bottle-homebrew-amd64'}
    GeneratedJob{name='ignition_math7-install_bottle-homebrew-amd64'}
    GeneratedJob{name='ignition_msgs9-install_bottle-homebrew-amd64'}
    GeneratedJob{name='ignition_physics6-install_bottle-homebrew-amd64'}
    GeneratedJob{name='ignition_plugin2-install_bottle-homebrew-amd64'}
    GeneratedJob{name='ignition_rendering7-install_bottle-homebrew-amd64'}
    GeneratedJob{name='ignition_sensors7-install_bottle-homebrew-amd64'}
    GeneratedJob{name='ignition_tools2-install_bottle-homebrew-amd64'}
    GeneratedJob{name='ignition_transport12-install_bottle-homebrew-amd64'}
    GeneratedJob{name='ignition_utils2-install_bottle-homebrew-amd64'}
~~~

**Comment by j-rivero** [comment]
Changes:
```diff
Only in /tmp/pr_xml_configuration: gz_cmake3-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_common5-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_fuel-tools8-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_gui7-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_launch6-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_math7-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_msgs9-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_physics6-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_plugin2-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_rendering7-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_sensors7-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_sim-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_tools2-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_transport12-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: gz_utils2-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_cmake3-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_cmake3-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_common5-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_common5-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_fuel-tools8-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_fuel-tools8-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_gazebo-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_gazebo-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_gui7-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_gui7-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_launch6-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_launch6-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_math7-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_math7-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_msgs9-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_msgs9-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_physics6-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_physics6-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_plugin2-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_plugin2-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_rendering7-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_rendering7-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_sensors7-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_sensors7-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_tools2-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_tools2-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_transport12-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_transport12-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_utils2-install-pkg-focal-amd64.xml
Only in /tmp/pr_xml_configuration: ignition_utils2-install_bottle-homebrew-amd64.xml
```

**Comment by j-rivero** [comment]
Probably conflict with https://github.com/gazebo-tooling/release-tools/pull/838

**Comment by scpeters** [comment]
> Probably conflicts with #838

sorry about that! I need to do better about reviewing your pull requests, and then I would know which ones are already open! Yours is much better; closing.

**Pull request closed without merging**
