### PR TITLE
Change homebrew -ci- daily jobs to use gz-collections.yaml 

### PR DESCRIPTION
**Pull request by j-rivero**
Move Brew jobs to be generated by gz-collections.yaml.

Mainly reuse a good bunch of the code in `gazebo_libs` and include a brew generating function f4fa9305b50de3c2b07717b27073de014aacd322 and remove the current jobs generated by `ignition.dsl` in 83eab4b4e1d8d72b90d93c2802a4fc6f755d6c2b

### CODE REVIEW

**Comment by j-rivero** [comment]
Log of jobs generated:
```diff
diff -ur /tmp/current_log_generated/jobs.txt /tmp/pr_log_generated/jobs.txt
--- /tmp/current_log_generated/jobs.txt	2023-11-07 13:18:38.364251236 +0000
+++ /tmp/pr_log_generated/jobs.txt	2023-11-07 13:17:13.437639022 +0000
@@ -1,82 +1,162 @@
+branch_ci __upcoming__ gz_tools-ci-main-homebrew-amd64
 branch_ci __upcoming__ gz_tools-ci-main-jammy-amd64
 branch_ci citadel ign_cmake-ci-ign-cmake2-bionic-amd64
+branch_ci citadel ign_cmake-ci-ign-cmake2-homebrew-amd64
 branch_ci citadel ign_common-ci-ign-common3-bionic-amd64
+branch_ci citadel ign_common-ci-ign-common3-homebrew-amd64
 branch_ci citadel ign_fuel_tools-ci-ign-fuel-tools4-bionic-amd64
+branch_ci citadel ign_fuel_tools-ci-ign-fuel-tools4-homebrew-amd64
 branch_ci citadel ign_gazebo-ci-ign-gazebo3-bionic-amd64
+branch_ci citadel ign_gazebo-ci-ign-gazebo3-homebrew-amd64
 branch_ci citadel ign_gui-ci-ign-gui3-bionic-amd64
+branch_ci citadel ign_gui-ci-ign-gui3-homebrew-amd64
 branch_ci citadel ign_launch-ci-ign-launch2-bionic-amd64
+branch_ci citadel ign_launch-ci-ign-launch2-homebrew-amd64
 branch_ci citadel ign_math-ci-ign-math6-bionic-amd64
+branch_ci citadel ign_math-ci-ign-math6-homebrew-amd64
 branch_ci citadel ign_msgs-ci-ign-msgs5-bionic-amd64
+branch_ci citadel ign_msgs-ci-ign-msgs5-homebrew-amd64
 branch_ci citadel ign_physics-ci-ign-physics2-bionic-amd64
+branch_ci citadel ign_physics-ci-ign-physics2-homebrew-amd64
 branch_ci citadel ign_plugin-ci-ign-plugin1-bionic-amd64
+branch_ci citadel ign_plugin-ci-ign-plugin1-homebrew-amd64
 branch_ci citadel ign_rendering-ci-ign-rendering3-bionic-amd64
+branch_ci citadel ign_rendering-ci-ign-rendering3-homebrew-amd64
 branch_ci citadel ign_sensors-ci-ign-sensors3-bionic-amd64
+branch_ci citadel ign_sensors-ci-ign-sensors3-homebrew-amd64
 branch_ci citadel ign_tools-ci-ign-tools1-bionic-amd64
+branch_ci citadel ign_tools-ci-ign-tools1-homebrew-amd64
 branch_ci citadel ign_transport-ci-ign-transport8-bionic-amd64
+branch_ci citadel ign_transport-ci-ign-transport8-homebrew-amd64
 branch_ci citadel sdformat-ci-sdf9-bionic-amd64
+branch_ci citadel sdformat-ci-sdf9-homebrew-amd64
 branch_ci fortress gz_cmake-ci-ign-cmake2-focal-amd64
+branch_ci fortress gz_cmake-ci-ign-cmake2-homebrew-amd64
 branch_ci fortress gz_common-ci-ign-common4-focal-amd64
+branch_ci fortress gz_common-ci-ign-common4-homebrew-amd64
 branch_ci fortress gz_fuel_tools-ci-ign-fuel-tools7-focal-amd64
+branch_ci fortress gz_fuel_tools-ci-ign-fuel-tools7-homebrew-amd64
 branch_ci fortress gz_gui-ci-ign-gui6-focal-amd64
+branch_ci fortress gz_gui-ci-ign-gui6-homebrew-amd64
 branch_ci fortress gz_launch-ci-ign-launch5-focal-amd64
+branch_ci fortress gz_launch-ci-ign-launch5-homebrew-amd64
 branch_ci fortress gz_math-ci-ign-math6-focal-amd64
+branch_ci fortress gz_math-ci-ign-math6-homebrew-amd64
 branch_ci fortress gz_msgs-ci-ign-msgs8-focal-amd64
+branch_ci fortress gz_msgs-ci-ign-msgs8-homebrew-amd64
 branch_ci fortress gz_physics-ci-ign-physics5-focal-amd64
+branch_ci fortress gz_physics-ci-ign-physics5-homebrew-amd64
 branch_ci fortress gz_plugin-ci-ign-plugin1-focal-amd64
+branch_ci fortress gz_plugin-ci-ign-plugin1-homebrew-amd64
 branch_ci fortress gz_rendering-ci-ign-rendering6-focal-amd64
+branch_ci fortress gz_rendering-ci-ign-rendering6-homebrew-amd64
 branch_ci fortress gz_sensors-ci-ign-sensors6-focal-amd64
+branch_ci fortress gz_sensors-ci-ign-sensors6-homebrew-amd64
 branch_ci fortress gz_sim-ci-ign-sim6-focal-amd64
+branch_ci fortress gz_sim-ci-ign-sim6-homebrew-amd64
 branch_ci fortress gz_tools-ci-ign-tools1-focal-amd64
+branch_ci fortress gz_tools-ci-ign-tools1-homebrew-amd64
 branch_ci fortress gz_transport-ci-ign-transport11-focal-amd64
+branch_ci fortress gz_transport-ci-ign-transport11-homebrew-amd64
 branch_ci fortress gz_utils-ci-ign-utils1-focal-amd64
+branch_ci fortress gz_utils-ci-ign-utils1-homebrew-amd64
 branch_ci fortress sdformat-ci-sdf12-focal-amd64
+branch_ci fortress sdformat-ci-sdf12-homebrew-amd64
 branch_ci garden gz_cmake-ci-gz-cmake3-focal-amd64
+branch_ci garden gz_cmake-ci-gz-cmake3-homebrew-amd64
 branch_ci garden gz_common-ci-gz-common5-focal-amd64
+branch_ci garden gz_common-ci-gz-common5-homebrew-amd64
 branch_ci garden gz_fuel_tools-ci-gz-fuel-tools8-focal-amd64
+branch_ci garden gz_fuel_tools-ci-gz-fuel-tools8-homebrew-amd64
 branch_ci garden gz_gui-ci-gz-gui7-focal-amd64
+branch_ci garden gz_gui-ci-gz-gui7-homebrew-amd64
 branch_ci garden gz_launch-ci-gz-launch6-focal-amd64
+branch_ci garden gz_launch-ci-gz-launch6-homebrew-amd64
 branch_ci garden gz_math-ci-gz-math7-focal-amd64
+branch_ci garden gz_math-ci-gz-math7-homebrew-amd64
 branch_ci garden gz_msgs-ci-gz-msgs9-focal-amd64
+branch_ci garden gz_msgs-ci-gz-msgs9-homebrew-amd64
 branch_ci garden gz_physics-ci-gz-physics6-focal-amd64
+branch_ci garden gz_physics-ci-gz-physics6-homebrew-amd64
 branch_ci garden gz_plugin-ci-gz-plugin2-focal-amd64
+branch_ci garden gz_plugin-ci-gz-plugin2-homebrew-amd64
 branch_ci garden gz_rendering-ci-gz-rendering7-focal-amd64
+branch_ci garden gz_rendering-ci-gz-rendering7-homebrew-amd64
 branch_ci garden gz_sensors-ci-gz-sensors7-focal-amd64
+branch_ci garden gz_sensors-ci-gz-sensors7-homebrew-amd64
 branch_ci garden gz_sim-ci-gz-sim7-focal-amd64
+branch_ci garden gz_sim-ci-gz-sim7-homebrew-amd64
 branch_ci garden gz_tools-ci-gz-tools2-focal-amd64
+branch_ci garden gz_tools-ci-gz-tools2-homebrew-amd64
 branch_ci garden gz_transport-ci-gz-transport12-focal-amd64
+branch_ci garden gz_transport-ci-gz-transport12-homebrew-amd64
 branch_ci garden gz_utils-ci-gz-utils2-focal-amd64
+branch_ci garden gz_utils-ci-gz-utils2-homebrew-amd64
 branch_ci garden sdformat-ci-sdf13-focal-amd64
+branch_ci garden sdformat-ci-sdf13-homebrew-amd64
+branch_ci harmonic gz_cmake-ci-gz-cmake3-homebrew-amd64
 branch_ci harmonic gz_cmake-ci-gz-cmake3-jammy-amd64
+branch_ci harmonic gz_common-ci-gz-common5-homebrew-amd64
 branch_ci harmonic gz_common-ci-gz-common5-jammy-amd64
+branch_ci harmonic gz_fuel_tools-ci-gz-fuel-tools9-homebrew-amd64
 branch_ci harmonic gz_fuel_tools-ci-gz-fuel-tools9-jammy-amd64
+branch_ci harmonic gz_gui-ci-gz-gui8-homebrew-amd64
 branch_ci harmonic gz_gui-ci-gz-gui8-jammy-amd64
+branch_ci harmonic gz_launch-ci-gz-launch7-homebrew-amd64
 branch_ci harmonic gz_launch-ci-gz-launch7-jammy-amd64
+branch_ci harmonic gz_math-ci-gz-math7-homebrew-amd64
 branch_ci harmonic gz_math-ci-gz-math7-jammy-amd64
+branch_ci harmonic gz_msgs-ci-gz-msgs10-homebrew-amd64
 branch_ci harmonic gz_msgs-ci-gz-msgs10-jammy-amd64
+branch_ci harmonic gz_physics-ci-gz-physics7-homebrew-amd64
 branch_ci harmonic gz_physics-ci-gz-physics7-jammy-amd64
+branch_ci harmonic gz_plugin-ci-gz-plugin2-homebrew-amd64
 branch_ci harmonic gz_plugin-ci-gz-plugin2-jammy-amd64
+branch_ci harmonic gz_rendering-ci-gz-rendering8-homebrew-amd64
 branch_ci harmonic gz_rendering-ci-gz-rendering8-jammy-amd64
+branch_ci harmonic gz_sensors-ci-gz-sensors8-homebrew-amd64
 branch_ci harmonic gz_sensors-ci-gz-sensors8-jammy-amd64
+branch_ci harmonic gz_sim-ci-gz-sim8-homebrew-amd64
 branch_ci harmonic gz_sim-ci-gz-sim8-jammy-amd64
+branch_ci harmonic gz_tools-ci-gz-tools2-homebrew-amd64
 branch_ci harmonic gz_tools-ci-gz-tools2-jammy-amd64
+branch_ci harmonic gz_transport-ci-gz-transport13-homebrew-amd64
 branch_ci harmonic gz_transport-ci-gz-transport13-jammy-amd64
+branch_ci harmonic gz_utils-ci-gz-utils2-homebrew-amd64
 branch_ci harmonic gz_utils-ci-gz-utils2-jammy-amd64
+branch_ci harmonic sdformat-ci-sdf14-homebrew-amd64
 branch_ci harmonic sdformat-ci-sdf14-jammy-amd64
+branch_ci ionic gz_cmake-ci-main-homebrew-amd64
 branch_ci ionic gz_cmake-ci-main-jammy-amd64
+branch_ci ionic gz_common-ci-main-homebrew-amd64
 branch_ci ionic gz_common-ci-main-jammy-amd64
+branch_ci ionic gz_fuel_tools-ci-main-homebrew-amd64
 branch_ci ionic gz_fuel_tools-ci-main-jammy-amd64
+branch_ci ionic gz_gui-ci-main-homebrew-amd64
 branch_ci ionic gz_gui-ci-main-jammy-amd64
+branch_ci ionic gz_launch-ci-main-homebrew-amd64
 branch_ci ionic gz_launch-ci-main-jammy-amd64
+branch_ci ionic gz_math-ci-main-homebrew-amd64
 branch_ci ionic gz_math-ci-main-jammy-amd64
+branch_ci ionic gz_msgs-ci-main-homebrew-amd64
 branch_ci ionic gz_msgs-ci-main-jammy-amd64
+branch_ci ionic gz_physics-ci-main-homebrew-amd64
 branch_ci ionic gz_physics-ci-main-jammy-amd64
+branch_ci ionic gz_plugin-ci-main-homebrew-amd64
 branch_ci ionic gz_plugin-ci-main-jammy-amd64
+branch_ci ionic gz_rendering-ci-main-homebrew-amd64
 branch_ci ionic gz_rendering-ci-main-jammy-amd64
+branch_ci ionic gz_sensors-ci-main-homebrew-amd64
 branch_ci ionic gz_sensors-ci-main-jammy-amd64
+branch_ci ionic gz_sim-ci-main-homebrew-amd64
 branch_ci ionic gz_sim-ci-main-jammy-amd64
+branch_ci ionic gz_tools-ci-gz-tools2-homebrew-amd64
 branch_ci ionic gz_tools-ci-gz-tools2-jammy-amd64
+branch_ci ionic gz_transport-ci-main-homebrew-amd64
 branch_ci ionic gz_transport-ci-main-jammy-amd64
+branch_ci ionic gz_utils-ci-main-homebrew-amd64
 branch_ci ionic gz_utils-ci-main-jammy-amd64
+branch_ci ionic sdformat-ci-main-homebrew-amd64
 branch_ci ionic sdformat-ci-main-jammy-amd64
 unofficial_wrappers_install_pkg_ci garden ros_gzgarden_bridge-install-pkg_humble-ci-jammy-amd64
 unofficial_wrappers_install_pkg_ci garden ros_gzgarden_bridge-install-pkg_iron-ci-jammy-amd64
```

**Comment by j-rivero** [comment]
Ouch missing to remove the sdformat.dsl instances.

**Comment by j-rivero** [comment]
This does not look good:
```diff
--- /tmp/current_xml_configuration/sdformat-ci-main-homebrew-amd64.xml	2023-11-07 18:23:48.391787168 +0000
+++ /tmp/pr_xml_configuration/sdformat-ci-main-homebrew-amd64.xml	2023-11-07 18:21:11.675658992 +0000
@@ -34,7 +34,7 @@
             <priority>300</priority>
         </jenkins.advancedqueue.priority.strategy.PriorityJobProperty>
         <com.coravy.hudson.plugins.github.GithubProjectProperty>
-            <projectUrl>https://github.com/gazebosim/sdformat/</projectUrl>
+            <projectUrl>https://github.com/main/</projectUrl>
         </com.coravy.hudson.plugins.github.GithubProjectProperty>
     </properties>
     <canRoam>false</canRoam>
@@ -46,6 +46,10 @@
             <spec>@daily</spec>
             <ignorePostCommitHooks>false</ignorePostCommitHooks>
         </hudson.triggers.SCMTrigger>
+        <hudson.triggers.SCMTrigger>
+            <spec>@daily</spec>
+            <ignorePostCommitHooks>false</ignorePostCommitHooks>
+        </hudson.triggers.SCMTrigger>
     </triggers>
     <concurrentBuild>true</concurrentBuild>
     <builders>
@@ -69,7 +73,7 @@
         <hudson.tasks.Shell>
             <command>#!/bin/bash -xe
 
-/bin/bash -xe ./scripts/jenkins-scripts/sdformat-default-devel-homebrew-amd64.bash
+/bin/bash -xe "./scripts/jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash" "sdformat"
 </command>
         </hudson.tasks.Shell>
     </builders>
@@ -286,6 +290,13 @@
                     <reportEncoding></reportEncoding>
                     <skipSymbolicLinks>false</skipSymbolicLinks>
                 </io.jenkins.plugins.analysis.warnings.Clang>
+                <io.jenkins.plugins.analysis.warnings.Cmake>
+                    <id></id>
+                    <name></name>
+                    <pattern></pattern>
+                    <reportEncoding></reportEncoding>
+                    <skipSymbolicLinks>false</skipSymbolicLinks>
+                </io.jenkins.plugins.analysis.warnings.Cmake>
             </analysisTools>
             <sourceCodeEncoding></sourceCodeEncoding>
             <ignoreQualityGate>false</ignoreQualityGate>
@@ -324,12 +335,12 @@
     <scm class='hudson.plugins.git.GitSCM'>
         <userRemoteConfigs>
             <hudson.plugins.git.UserRemoteConfig>
-                <url>https://github.com/gazebosim/sdformat.git</url>
+                <url>https://github.com/main.git</url>
             </hudson.plugins.git.UserRemoteConfig>
         </userRemoteConfigs>
         <branches>
             <hudson.plugins.git.BranchSpec>
-                <name>main</name>
+                <name>sdformat</name>
             </hudson.plugins.git.BranchSpec>
         </branches>
         <configVersion>2</configVersion>
@@ -337,11 +348,11 @@
         <gitTool>Default</gitTool>
         <extensions>
             <hudson.plugins.git.extensions.impl.RelativeTargetDirectory>
-                <relativeTargetDir>sdformat</relativeTargetDir>
+                <relativeTargetDir>main</relativeTargetDir>
             </hudson.plugins.git.extensions.impl.RelativeTargetDirectory>
         </extensions>
         <browser class='hudson.plugins.git.browser.GithubWeb'>
-            <url>https://github.com/gazebosim/sdformat/</url>
+            <url>https://github.com/main/</url>
         </browser>
     </scm>
 </project>
```

**Comment by j-rivero** [comment]
Fixed problems with github repositories and implemented a check in [2ac0547](https://github.com/gazebo-tooling/release-tools/pull/1058/commits/2ac05476d6fb38033a28e049779540d24c2f71fa). Diff from current job, for example gz-common5:
```diff
--- /tmp/master/ignition_common-ci-gz-common5-homebrew-amd64.xml	2023-11-08 18:11:31.753141963 +0100
+++ gz_common-ci-gz-common5-homebrew-amd64.xml	2023-11-08 18:19:33.028659331 +0100
@@ -69,15 +69,13 @@
         <hudson.tasks.Shell>
             <command>#!/bin/bash -xe
 
-software_name="gz-common"
-[[ common == 'gazebo' ]] &amp;&amp; software_name="gz-sim"
-/bin/bash -xe "./scripts/jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash" "${software_name}"
+/bin/bash -xe ./scripts/jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash "gz-common"
 </command>
         </hudson.tasks.Shell>
     </builders>
     <publishers>
         <hudson.plugins.emailext.ExtendedEmailPublisher>
-            <recipientList>$DEFAULT_RECIPIENTS, caguero@osrfoundation.org</recipientList>
+            <recipientList>$DEFAULT_RECIPIENTS</recipientList>
             <configuredTriggers>
                 <hudson.plugins.emailext.plugins.trigger.FailureTrigger>
                     <email>
@@ -339,7 +337,7 @@
         <gitTool>Default</gitTool>
         <extensions>
             <hudson.plugins.git.extensions.impl.RelativeTargetDirectory>
-                <relativeTargetDir>ign-common</relativeTargetDir>
+                <relativeTargetDir>gz-common</relativeTargetDir>
             </hudson.plugins.git.extensions.impl.RelativeTargetDirectory>
         </extensions>
         <browser class='hudson.plugins.git.browser.GithubWeb'>

```

**Comment by j-rivero** [comment]
@Crola1702 @Blast545  this is ready to go. Windows ci for branches should land soon after this which will complete the branch CI testing.

**Comment by j-rivero** [comment]
Seems to work fine https://build.osrfoundation.org/job/gz_gui-ci-gz-gui7-homebrew-amd64/1/

**Comment by Crola1702** [comment]
@j-rivero, do you have any estimate on when the Windows changes will come?

**Comment by j-rivero** [comment]
> @j-rivero, do you have any estimate on when the Windows changes will come?

I have, today probably :)

**Pull request merged**
