### PR TITLE
Replace /usr/local with HOMEBREW_PREFIX part 1

### PR DESCRIPTION
**Pull request by scpeters**
One of our brew build scripts has a `HOMEBREW_PREFIX` variable to represent the location where brew is installed (either `/usr/local` for Intel macOS machines or `/opt/homebrew` for arm macOS machines), but it also has many paths hard-coded to /usr/local. In preparation for supporting arm-based CI machines, use the `HOMEBREW_PREFIX` variable more widely.

### CODE REVIEW

**Review by claraberendsen — COMMENTED** [review]
Thanks @scpeters for setting this up! A quick question related to the name of the bash script ... since we are generalizing it, would it make sense to update the name to be `project-default-devel-homebrew.bash`?  
I'm not sure if there are more  particularities in the script that would make keeping the `amd64` naming still worth it.

**Comment by scpeters** [comment]
> Thanks @scpeters for setting this up! A quick question related to the name of the bash script ... since we are generalizing it, would it make sense to update the name to be `project-default-devel-homebrew.bash`? I'm not sure if there are more particularities in the script that would make keeping the `amd64` naming still worth it.

I'm fine with changing the name of the script, though it's not quite generalized yet.

**Comment by scpeters** [comment]
> > Thanks @scpeters for setting this up! A quick question related to the name of the bash script ... since we are generalizing it, would it make sense to update the name to be `project-default-devel-homebrew.bash`? I'm not sure if there are more particularities in the script that would make keeping the `amd64` naming still worth it.
> 
> I'm fine with changing the name of the script, though it's not quite generalized yet.

I'd also prefer to change it in a separate pull request to keep the changes from getting mixed together

**Comment by j-rivero** [comment]
> I'd also prefer to change it in a separate pull request to keep the changes from getting mixed together

+1

**Comment by j-rivero** [comment]
we have a few more places that use usr/local/bin for populating the BREW_BINARY_DIR variable:
```bash
release-tools/jenkins-scripts on  scpeters/brew_prefix [?] ❯ grep -r local/bin  lib/
lib/_homebrew_base_setup.bash:BREW_BINARY_DIR=/usr/local/bin
lib/homebrew_bottle_creation.bash:export PATH="/usr/local/bin:$PATH"
lib/_homebrew_cleanup.bash:BREW_BINARY_DIR=/usr/local/bin
```

Do we need to change these too?

**Comment by scpeters** [comment]
> we have a few more places that use usr/local/bin for populating the BREW_BINARY_DIR variable:
> 
> ```shell
> release-tools/jenkins-scripts on  scpeters/brew_prefix [?] ❯ grep -r local/bin  lib/
> lib/_homebrew_base_setup.bash:BREW_BINARY_DIR=/usr/local/bin
> lib/homebrew_bottle_creation.bash:export PATH="/usr/local/bin:$PATH"
> lib/_homebrew_cleanup.bash:BREW_BINARY_DIR=/usr/local/bin
> ```
> 
> Do we need to change these too?

The challenge that I didn't try to address here is how to get the `brew` command in your `PATH`, which is what most of these instances are doing. When you install `brew` on Intel to `/usr/local`, it should already be in your path, so you can just execute `brew --prefix`, but on arm64 it installs to `/opt/homebrew` and recommends in the [console output after installation](https://github.com/Homebrew/install/blob/cc1a94045eeacbb80bfc37250f1659f542bc5c83/install.sh#L1047-L1063) to `eval` the [brew shellcheck](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/shellenv.rb) command in a terminal or in your shell rc file to add `brew` to your `PATH`.

I feel like that is something that should be preconfigured on the build machine but am not sure where we currently configure that. Once we've addressed that, we can clean this up further. For this PR, I was just cleaning up a file that already defines `HOMEBREW_PREFIX` at the top of the file but wasn't using it throughout. So this is an incremental step.

**Comment by j-rivero** [comment]
> I feel like that is something that should be preconfigured on the build machine but am not sure where we currently configure that.

There are environments variable that we can configure per-node when we provision them. We probably could use that.

> For this PR, I was just cleaning up a file that already defines HOMEBREW_PREFIX at the top of the file but wasn't using it throughout. So this is an incremental step.

Understood, thanks for clarifying.

**Review by j-rivero — APPROVED** [review]

**Pull request merged**
