### PR TITLE
Update outdated-job-runner job list

### PR DESCRIPTION
**Pull request by Crola1702**
After https://github.com/gazebo-tooling/release-tools/pull/1047, naming on garden, fortress, and citadel changed for Linux

This PR updates the job list for periodic runs

### CODE REVIEW

**Review by Blast545 — APPROVED** [review]
Do we have any way to check this script before merging pull requests changes to it? Or compare it against our internal common.py?

Something to think about once you are back.

**Comment by j-rivero** [comment]
Side note: it would be great to use the output of the own job generation (see https://github.com/gazebo-tooling/release-tools/pull/985) to somehow feed this list. Not for this PR but a nice future work.

**Comment by claraberendsen** [comment]
> Side note: it would be great to use the output of the own job generation (see #985) to somehow feed this list. Not for this PR but a nice future work.

Agreed that it would be nice to connect it to the changes on the dsl jobs. I will add it to our backlog for future work.

**Review by claraberendsen — APPROVED** [review]
This LGTM in terms of getting us up to date with the current approach. However for these names I think we should push to have one source of truth that we fetched this information from rather than manually updating each time, given that this affects us a couple of number of times in the year.

**Comment by claraberendsen** [comment]
@Blast545 feel free to merge this as is for now, and let's add a new tasks on how we can keep this list up-to-date with the changes in the jobs.

**Pull request merged**
