### PR TITLE
Bump versions for main and setup nightlies

### PR DESCRIPTION
**Pull request by iche033**
* bump major version for all upcoming libraries
* setup nightlies for upcoming libs
* removed nightlies for ionic

### CODE REVIEW

**Comment by j-rivero** [comment]
One of the TODOs still in the release-tools repo coming from ignition is the nightly distribution declaration that should go in https://github.com/gazebo-tooling/release-tools/blob/master/jenkins-scripts/dsl/ignition_collection.dsl#L14 . That needs to be moved to the current yaml configuration. I changed it in [96ee8a9](https://github.com/gazebo-tooling/release-tools/pull/1188/commits/96ee8a93eb1e266166ced53f420b3d5c5726f52f).

**Comment by j-rivero** [comment]
Content changed:
```diff
diff -ur -I '.*<id>dashboard_portlet_.*</id>.*' /tmp/current_xml_configuration/gz-__upcoming__.xml /tmp/pr_xml_configuration/gz-__upcoming__.xml
--- /tmp/current_xml_configuration/gz-__upcoming__.xml	2024-10-30 12:00:41.468188352 +0000
+++ /tmp/pr_xml_configuration/gz-__upcoming__.xml	2024-10-30 11:59:13.219977937 +0000
@@ -4,78 +4,93 @@
     <properties class='hudson.model.View$PropertyList'></properties>
     <jobNames>
         <comparator class='hudson.util.CaseInsensitiveComparator'></comparator>
+        <string>gz-cmake5-debbuilder</string>
+        <string>gz-common7-debbuilder</string>
+        <string>gz-fuel-tools11-debbuilder</string>
+        <string>gz-gui10-debbuilder</string>
+        <string>gz-launch9-debbuilder</string>
+        <string>gz-math9-debbuilder</string>
+        <string>gz-msgs12-debbuilder</string>
+        <string>gz-physics9-debbuilder</string>
+        <string>gz-plugin4-debbuilder</string>
+        <string>gz-rendering10-debbuilder</string>
+        <string>gz-sensors10-debbuilder</string>
+        <string>gz-sim10-debbuilder</string>
+        <string>gz-tools3-debbuilder</string>
+        <string>gz-transport15-debbuilder</string>
+        <string>gz-utils4-debbuilder</string>
         <string>gz_cmake-ci-main-homebrew-amd64</string>
         <string>gz_cmake-ci-main-noble-amd64</string>
         <string>gz_cmake-ci_asan-main-noble-amd64</string>
         <string>gz_cmake-main-win</string>
-        <string>gz_cmake4-install-pkg-noble-amd64</string>
-        <string>gz_cmake4-install_bottle-homebrew-amd64</string>
+        <string>gz_cmake5-install-pkg-noble-amd64</string>
+        <string>gz_cmake5-install_bottle-homebrew-amd64</string>
         <string>gz_common-ci-main-homebrew-amd64</string>
         <string>gz_common-ci-main-noble-amd64</string>
         <string>gz_common-ci_asan-main-noble-amd64</string>
         <string>gz_common-main-win</string>
-        <string>gz_common6-install-pkg-noble-amd64</string>
-        <string>gz_common6-install_bottle-homebrew-amd64</string>
+        <string>gz_common7-install-pkg-noble-amd64</string>
+        <string>gz_common7-install_bottle-homebrew-amd64</string>
         <string>gz_fuel_tools-ci-main-homebrew-amd64</string>
         <string>gz_fuel_tools-ci-main-noble-amd64</string>
         <string>gz_fuel_tools-ci_asan-main-noble-amd64</string>
         <string>gz_fuel_tools-main-win</string>
-        <string>gz_fuel_tools10-install-pkg-noble-amd64</string>
-        <string>gz_fuel_tools10-install_bottle-homebrew-amd64</string>
+        <string>gz_fuel_tools11-install-pkg-noble-amd64</string>
+        <string>gz_fuel_tools11-install_bottle-homebrew-amd64</string>
         <string>gz_gui-ci-main-homebrew-amd64</string>
         <string>gz_gui-ci-main-noble-amd64</string>
         <string>gz_gui-ci_asan-main-noble-amd64</string>
         <string>gz_gui-main-win</string>
-        <string>gz_gui9-install-pkg-noble-amd64</string>
-        <string>gz_gui9-install_bottle-homebrew-amd64</string>
+        <string>gz_gui10-install-pkg-noble-amd64</string>
+        <string>gz_gui10-install_bottle-homebrew-amd64</string>
         <string>gz_launch-ci-main-homebrew-amd64</string>
         <string>gz_launch-ci-main-noble-amd64</string>
         <string>gz_launch-ci_asan-main-noble-amd64</string>
         <string>gz_launch-main-win</string>
-        <string>gz_launch8-install-pkg-noble-amd64</string>
-        <string>gz_launch8-install_bottle-homebrew-amd64</string>
+        <string>gz_launch9-install-pkg-noble-amd64</string>
+        <string>gz_launch9-install_bottle-homebrew-amd64</string>
         <string>gz_math-ci-main-homebrew-amd64</string>
         <string>gz_math-ci-main-noble-amd64</string>
         <string>gz_math-ci_asan-main-noble-amd64</string>
         <string>gz_math-main-win</string>
-        <string>gz_math8-install-pkg-noble-amd64</string>
-        <string>gz_math8-install_bottle-homebrew-amd64</string>
+        <string>gz_math9-install-pkg-noble-amd64</string>
+        <string>gz_math9-install_bottle-homebrew-amd64</string>
         <string>gz_msgs-ci-main-homebrew-amd64</string>
         <string>gz_msgs-ci-main-noble-amd64</string>
         <string>gz_msgs-ci_asan-main-noble-amd64</string>
         <string>gz_msgs-main-win</string>
-        <string>gz_msgs11-install-pkg-noble-amd64</string>
-        <string>gz_msgs11-install_bottle-homebrew-amd64</string>
+        <string>gz_msgs12-install-pkg-noble-amd64</string>
+        <string>gz_msgs12-install_bottle-homebrew-amd64</string>
         <string>gz_physics-ci-main-homebrew-amd64</string>
         <string>gz_physics-ci-main-noble-amd64</string>
         <string>gz_physics-ci_asan-main-noble-amd64</string>
         <string>gz_physics-main-win</string>
-        <string>gz_physics8-install-pkg-noble-amd64</string>
-        <string>gz_physics8-install_bottle-homebrew-amd64</string>
+        <string>gz_physics9-install-pkg-noble-amd64</string>
+        <string>gz_physics9-install_bottle-homebrew-amd64</string>
         <string>gz_plugin-ci-main-homebrew-amd64</string>
         <string>gz_plugin-ci-main-noble-amd64</string>
         <string>gz_plugin-ci_asan-main-noble-amd64</string>
         <string>gz_plugin-main-win</string>
-        <string>gz_plugin3-install-pkg-noble-amd64</string>
-        <string>gz_plugin3-install_bottle-homebrew-amd64</string>
+        <string>gz_plugin4-install-pkg-noble-amd64</string>
+        <string>gz_plugin4-install_bottle-homebrew-amd64</string>
         <string>gz_rendering-ci-main-homebrew-amd64</string>
         <string>gz_rendering-ci-main-noble-amd64</string>
         <string>gz_rendering-ci_asan-main-noble-amd64</string>
         <string>gz_rendering-main-win</string>
-        <string>gz_rendering9-install-pkg-noble-amd64</string>
-        <string>gz_rendering9-install_bottle-homebrew-amd64</string>
+        <string>gz_rendering10-install-pkg-noble-amd64</string>
+        <string>gz_rendering10-install_bottle-homebrew-amd64</string>
         <string>gz_sensors-ci-main-homebrew-amd64</string>
         <string>gz_sensors-ci-main-noble-amd64</string>
         <string>gz_sensors-ci_asan-main-noble-amd64</string>
         <string>gz_sensors-main-win</string>
-        <string>gz_sensors9-install-pkg-noble-amd64</string>
-        <string>gz_sensors9-install_bottle-homebrew-amd64</string>
+        <string>gz_sensors10-install-pkg-noble-amd64</string>
+        <string>gz_sensors10-install_bottle-homebrew-amd64</string>
         <string>gz_sim-ci-main-homebrew-amd64</string>
         <string>gz_sim-ci-main-noble-amd64</string>
         <string>gz_sim-ci_asan-main-noble-amd64</string>
         <string>gz_sim-main-win</string>
-        <string>gz_sim9-install-pkg-noble-amd64</string>
-        <string>gz_sim9-install_bottle-homebrew-amd64</string>
+        <string>gz_sim10-install-pkg-noble-amd64</string>
+        <string>gz_sim10-install_bottle-homebrew-amd64</string>
         <string>gz_tools-ci-main-homebrew-amd64</string>
         <string>gz_tools-ci-main-noble-amd64</string>
         <string>gz_tools-ci_asan-main-noble-amd64</string>
@@ -86,20 +101,21 @@
         <string>gz_transport-ci-main-noble-amd64</string>
         <string>gz_transport-ci_asan-main-noble-amd64</string>
         <string>gz_transport-main-win</string>
-        <string>gz_transport14-install-pkg-noble-amd64</string>
-        <string>gz_transport14-install_bottle-homebrew-amd64</string>
+        <string>gz_transport15-install-pkg-noble-amd64</string>
+        <string>gz_transport15-install_bottle-homebrew-amd64</string>
         <string>gz_utils-ci-main-homebrew-amd64</string>
         <string>gz_utils-ci-main-noble-amd64</string>
         <string>gz_utils-ci_asan-main-noble-amd64</string>
         <string>gz_utils-main-win</string>
-        <string>gz_utils3-install-pkg-noble-amd64</string>
-        <string>gz_utils3-install_bottle-homebrew-amd64</string>
+        <string>gz_utils4-install-pkg-noble-amd64</string>
+        <string>gz_utils4-install_bottle-homebrew-amd64</string>
         <string>sdformat-ci-main-homebrew-amd64</string>
         <string>sdformat-ci-main-noble-amd64</string>
         <string>sdformat-ci_asan-main-noble-amd64</string>
         <string>sdformat-main-win</string>
-        <string>sdformat15-install-pkg-noble-amd64</string>
-        <string>sdformat15-install_bottle-homebrew-amd64</string>
+        <string>sdformat16-debbuilder</string>
+        <string>sdformat16-install-pkg-noble-amd64</string>
+        <string>sdformat16-install_bottle-homebrew-amd64</string>
     </jobNames>
     <jobFilters></jobFilters>
     <columns>
Only in /tmp/pr_xml_configuration: gz-cmake5-debbuilder.xml
Only in /tmp/pr_xml_configuration: gz-cmake5-source.xml
Only in /tmp/pr_xml_configuration: gz-common7-debbuilder.xml
Only in /tmp/pr_xml_configuration: gz-common7-source.xml
Only in /tmp/pr_xml_configuration: gz-fuel-tools11-debbuilder.xml
Only in /tmp/pr_xml_configuration: gz-fuel-tools11-source.xml
Only in /tmp/pr_xml_configuration: gz-gui10-debbuilder.xml
Only in /tmp/pr_xml_configuration: gz-gui10-source.xml
diff -ur -I '.*<id>dashboard_portlet_.*</id>.*' /tmp/current_xml_configuration/gz-ionic.xml /tmp/pr_xml_configuration/gz-ionic.xml
--- /tmp/current_xml_configuration/gz-ionic.xml	2024-10-30 12:00:41.388188245 +0000
+++ /tmp/pr_xml_configuration/gz-ionic.xml	2024-10-30 11:59:13.143977685 +0000
@@ -4,22 +4,6 @@
     <properties class='hudson.model.View$PropertyList'></properties>
     <jobNames>
         <comparator class='hudson.util.CaseInsensitiveComparator'></comparator>
-        <string>gz-cmake4-debbuilder</string>
-        <string>gz-common6-debbuilder</string>
-        <string>gz-fuel-tools10-debbuilder</string>
-        <string>gz-gui9-debbuilder</string>
-        <string>gz-ionic-debbuilder</string>
-        <string>gz-launch8-debbuilder</string>
-        <string>gz-math8-debbuilder</string>
-        <string>gz-msgs11-debbuilder</string>
-        <string>gz-physics8-debbuilder</string>
-        <string>gz-plugin3-debbuilder</string>
-        <string>gz-rendering9-debbuilder</string>
-        <string>gz-sensors9-debbuilder</string>
-        <string>gz-sim9-debbuilder</string>
-        <string>gz-tools2-debbuilder</string>
-        <string>gz-transport14-debbuilder</string>
-        <string>gz-utils3-debbuilder</string>
         <string>gz_cmake-4-win</string>
         <string>gz_cmake-ci-gz-cmake4-homebrew-amd64</string>
         <string>gz_cmake-ci-gz-cmake4-noble-amd64</string>
@@ -116,7 +100,6 @@
         <string>sdformat-ci-sdf15-noble-amd64</string>
         <string>sdformat-ci_asan-sdf15-noble-amd64</string>
         <string>sdformat-sdf15-win</string>
-        <string>sdformat15-debbuilder</string>
         <string>sdformat15-install-pkg-noble-amd64</string>
         <string>sdformat15-install_bottle-homebrew-amd64</string>
     </jobNames>
Only in /tmp/pr_xml_configuration: gz-launch9-debbuilder.xml
Only in /tmp/pr_xml_configuration: gz-launch9-source.xml
Only in /tmp/pr_xml_configuration: gz-math9-debbuilder.xml
Only in /tmp/pr_xml_configuration: gz-math9-source.xml
Only in /tmp/pr_xml_configuration: gz-msgs12-debbuilder.xml
Only in /tmp/pr_xml_configuration: gz-msgs12-source.xml
Only in /tmp/pr_xml_configuration: gz-physics9-debbuilder.xml
Only in /tmp/pr_xml_configuration: gz-physics9-source.xml
Only in /tmp/pr_xml_configuration: gz-plugin4-debbuilder.xml
Only in /tmp/pr_xml_configuration: gz-plugin4-source.xml
Only in /tmp/pr_xml_configuration: gz-rendering10-debbuilder.xml
Only in /tmp/pr_xml_configuration: gz-rendering10-source.xml
Only in /tmp/pr_xml_configuration: gz-sensors10-debbuilder.xml
Only in /tmp/pr_xml_configuration: gz-sensors10-source.xml
Only in /tmp/pr_xml_configuration: gz-sim10-debbuilder.xml
Only in /tmp/pr_xml_configuration: gz-sim10-source.xml
Only in /tmp/pr_xml_configuration: gz-transport15-debbuilder.xml
Only in /tmp/pr_xml_configuration: gz-transport15-source.xml
Only in /tmp/pr_xml_configuration: gz-utils4-debbuilder.xml
Only in /tmp/pr_xml_configuration: gz-utils4-source.xml
Only in /tmp/pr_xml_configuration: gz_cmake5-install-pkg-noble-amd64.xml
Only in /tmp/pr_xml_configuration: gz_cmake5-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: gz_common7-install-pkg-noble-amd64.xml
Only in /tmp/pr_xml_configuration: gz_common7-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: gz_fuel_tools11-install-pkg-noble-amd64.xml
Only in /tmp/pr_xml_configuration: gz_fuel_tools11-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: gz_gui10-install-pkg-noble-amd64.xml
Only in /tmp/pr_xml_configuration: gz_gui10-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: gz_launch9-install-pkg-noble-amd64.xml
Only in /tmp/pr_xml_configuration: gz_launch9-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: gz_math9-install-pkg-noble-amd64.xml
Only in /tmp/pr_xml_configuration: gz_math9-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: gz_msgs12-install-pkg-noble-amd64.xml
Only in /tmp/pr_xml_configuration: gz_msgs12-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: gz_physics9-install-pkg-noble-amd64.xml
Only in /tmp/pr_xml_configuration: gz_physics9-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: gz_plugin4-install-pkg-noble-amd64.xml
Only in /tmp/pr_xml_configuration: gz_plugin4-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: gz_rendering10-install-pkg-noble-amd64.xml
Only in /tmp/pr_xml_configuration: gz_rendering10-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: gz_sensors10-install-pkg-noble-amd64.xml
Only in /tmp/pr_xml_configuration: gz_sensors10-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: gz_sim10-install-pkg-noble-amd64.xml
Only in /tmp/pr_xml_configuration: gz_sim10-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: gz_transport15-install-pkg-noble-amd64.xml
Only in /tmp/pr_xml_configuration: gz_transport15-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: gz_utils4-install-pkg-noble-amd64.xml
Only in /tmp/pr_xml_configuration: gz_utils4-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: ignition-__upcoming__-nightly-scheduler.xml
Only in /tmp/current_xml_configuration: ignition-ionic-nightly-scheduler.xml
Only in /tmp/pr_xml_configuration: sdformat16-debbuilder.xml
Only in /tmp/pr_xml_configuration: sdformat16-install-pkg-noble-amd64.xml
Only in /tmp/pr_xml_configuration: sdformat16-install_bottle-homebrew-amd64.xml
Only in /tmp/pr_xml_configuration: sdformat16-source.xml
```

**Comment by iche033** [comment]
> One of the TODOs still in the release-tools repo coming from ignition is the nightly distribution declaration that should go in https://github.com/gazebo-tooling/release-tools/blob/master/jenkins-scripts/dsl/ignition_collection.dsl#L14 . That needs to be moved to the current yaml configuration. I changed it in [96ee8a9](https://github.com/gazebo-tooling/release-tools/pull/1188/commits/96ee8a93eb1e266166ced53f420b3d5c5726f52f).

thanks!

**Comment by j-rivero** [comment]
I'll merge it tomorrow / over the weekend to get fresh nightly results starting next week.

**Pull request merged**
